# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/case_transform/all/case_transform.rbi
#
# case_transform-0.2

module CaseTransform
  def self.camel(value); end
  def self.camel_cache; end
  def self.camel_lower(value); end
  def self.camel_lower_cache; end
  def self.dash(value); end
  def self.dash_cache; end
  def self.unaltered(value); end
  def self.underscore(value); end
  def self.underscore_cache; end
end
