# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rswag-api/all/rswag-api.rbi
#
# rswag-api-2.8.0

module Rswag
end
module Rswag::Api
  def self.config; end
  def self.configure; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
class Rswag::Api::Configuration
  def resolve_swagger_root(env); end
  def swagger_filter; end
  def swagger_filter=(arg0); end
  def swagger_headers; end
  def swagger_headers=(arg0); end
  def swagger_root; end
  def swagger_root=(arg0); end
end
class Rswag::Api::Middleware
  def call(env); end
  def initialize(app, config); end
  def load_json(filename); end
  def load_yaml(filename); end
  def parse_file(filename); end
  def unload_swagger(filename, swagger); end
end
class Rswag::Api::Engine < Rails::Engine
end
