# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rswag-ui/all/rswag-ui.rbi
#
# rswag-ui-2.4.0

module Rswag
end
module Rswag::Ui
  def self.config; end
  def self.configure; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
class Rswag::Ui::Configuration
  def assets_root; end
  def basic_auth_credentials(username, password); end
  def basic_auth_enabled; end
  def basic_auth_enabled=(arg0); end
  def config_object; end
  def config_object=(arg0); end
  def get_binding; end
  def initialize; end
  def oauth_config_object; end
  def oauth_config_object=(arg0); end
  def swagger_endpoint(url, name); end
  def template_locations; end
end
class Rswag::Ui::Middleware < Rack::Static
  def base_path?(env); end
  def call(env); end
  def index_path?(env); end
  def initialize(app, config); end
  def render_template; end
  def template_filename; end
end
class Rswag::Ui::BasicAuth < Rack::Auth::Basic
  def base_path(url); end
  def call(env); end
  def env_matching_path(env); end
end
class Rswag::Ui::Engine < Rails::Engine
end
