# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rutie/all/rutie.rbi
#
# rutie-0.0.4

class Rutie
  def ffi_library(dir); end
  def host_os; end
  def init(c_init_method_name, dir); end
  def initialize(project_name, **opts); end
  def lib_path(dir); end
  def operating_system; end
  def set_prefix; end
  def set_suffix; end
end
class Rutie::ProjectName
  def initialize(name); end
  def to_str; end
  def valid_name?(project); end
end
class Rutie::ProjectName::InvalidProjectName < StandardError
  def message; end
end
