# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rutie_task_handler/all/rutie_task_handler.rbi
#
# rutie_task_handler-0.1.0

module RutieTaskHandler
end
class RutieTaskHandler::Error < StandardError
end
class DummyRutieTaskHandler
  def self.handle(*arg0); end
end
